<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */
$viewModeldata = $block->getData('viewModel');
$getButtonEnable = $viewModeldata->getButtonEnable();
$gettile = $viewModeldata->getpdpTitle();
$getmodelheadertitle = $viewModeldata->getmodelheaderTitle();
$customerdata=$viewModeldata->getCustomer();
$fname=$customerdata['fname'];
$lname=$customerdata['lname'];
$cemail=$customerdata['email'];
$product = $block->getProduct();
$product_url=$product->getProductUrl();
$producttype=$product->getTypeId();
?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<?php $inputClass = 'checkbox product bundle option bundle-option-' . $block->escapeHtmlAttr($_option->getId()) ?>
<?php $inputId = 'bundle-option-' . $block->escapeHtmlAttr($_option->getId()) ?>
<?php $inputName = 'bundle_option[' . $block->escapeHtmlAttr($_option->getId()) . ']' ?>
<?php $dataValidation = 'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' .
    $block->escapeHtmlAttr($_option->getId()) . ']&quot;]:checked\'}"' ?>

<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selections[0]) ?>
                <input type="hidden"
                       class="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>  product bundle option"
                       name="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                       value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"/>
            <?php else: ?>
                <?php foreach ($_selections as $selection): ?>
                    <?php $sectionId = $selection->getSelectionId() ?>
                    <div class="field choice">
                        <input class="<?=/* @noEscape */ $inputClass ?> change-container-classname"
                               id="<?=/* @noEscape */ $inputId . '-' . $block->escapeHtmlAttr($sectionId)?>"
                               type="checkbox"
                               <?php if ($_option->getRequired()): ?>
                                    <?= /* @noEscape */ $dataValidation ?>
                               <?php endif;?>
                               name="<?=/* @noEscape */ $inputName .'['. $block->escapeHtmlAttr($sectionId)?>]"
                               data-selector="<?= /* @noEscape */ $inputName.'['.$block->escapeHtmlAttr($sectionId)?>]"
                                <?php if ($block->isSelected($selection)): ?>
                                    <?= ' checked="checked"' ?>
                                <?php endif; ?>
                                <?php if (!$selection->isSaleable()): ?>
                                    <?= ' disabled="disabled"' ?>
                                <?php endif; ?>
                               value="<?= $block->escapeHtmlAttr($sectionId) ?>"
                               data-errors-message-box="#validation-message-box"/>
                        <label class="label"
                               for="<?= /* @noEscape */ $inputId . '-' . $block->escapeHtmlAttr($sectionId) ?>">
                            <span><?= /* @noEscape */ $block->getSelectionQtyTitlePrice($selection) ?></span>
                            <br/>
                            <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($selection) ?>
                        </label>
                    </div>
                    <?php
                    $sku=$selection->getSku();
                    $pname=$selection->getName();
                    $pid=$selection->getId();
                    $isAvailable=$selection->isAvailable();
                    ?>
                    <?php if ($getButtonEnable && $isAvailable=='0'): ?>
                        <div>
                        <a href="javascript:void(0);" class="enquiry-product-group pdpbutton bundle"
                        data-sku='<?= /* @noEscape */
                        $sku; ?>' data-title="<?= /* @noEscape */
                        $getmodelheadertitle; ?>" 
                        id="enquiry-product-group<?= /* @noEscape */ $sku; ?>"><?= /* @noEscape */ $gettile; ?></a>
                        </div>
                        <div id="popup-modalgroup<?= /* @noEscape */ $sku; ?>" style="display:none;">
                        <div id='responcedata<?= /* @noEscape */ $sku; ?>'></div>
                        <div class="formdata" id='formdata<?= /* @noEscape */ $sku; ?>'>
                        <input type="hidden" value="<?= /* @noEscape */ $pid; ?>" name='pid' 
                        id='pid<?= /* @noEscape */ $sku; ?>'>
                        <input type="hidden" value="<?= /* @noEscape */ $product_url; ?>" name='product_url' 
                        id='product_url<?= /* @noEscape */ $sku; ?>'>    
                        <input type="hidden" value="<?= /* @noEscape */
                        $pname; ?>" name='pname' id='pname<?= /* @noEscape */
                        $sku; ?>'>
                        <input type="hidden" value="<?= /* @noEscape */ $sku; ?>" name='sku' 
                        id='sku<?= /* @noEscape */ $sku; ?>'>
                        <input type="text" value="<?= /* @noEscape */
                        $fname; ?>" name='fname' id='fname<?= /* @noEscape */
                        $sku; ?>' placeholder="First Name">
                        <input type="text" value="<?= /* @noEscape */
                        $lname; ?>" name='lname' id='lname<?= /* @noEscape */
                        $sku; ?>' placeholder="Last Name">
                        <input type="email" value="<?= /* @noEscape */
                        $cemail; ?>" name='email' id='email<?= /* @noEscape */
                        $sku; ?>' placeholder="Email">
                        <span class='Submit_Enquiry_btn' id="submit_stockenquire<?= /* @noEscape */ $sku; ?>">
                        <?= /* @noEscape */ $gettile; ?></span>
                        </div>
                    </div>
                    <?php endif; ?>
                <?php endforeach; ?>
                <div id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-container"></div>
                <div id="validation-message-box"></div>
            <?php endif; ?>
        </div>
    </div>
</div>
